services:
  - type: web
    name: medica-api
    runtime: docker
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: CORS_ORIGIN
        sync: false
